### ISSUE TITLE
Negative Temperature

### ISSUE THREAD

**Issue by bhutzler** [cbrandlehner/homebridge-luxtronik2#1]
If the temperature falls below 0 degrees Celsius, the Apple Home App shows "no response". As soon as the temperature is in the positive range, it is displayed normally.

**Comment by cbrandlehner** [comment]
Hi!
First of all I have to say I am happy that I am not the only one to use this. :-)
I have not checked this during winter and now it's too warm to see in real life. I will try to find out what goes wrong. However, do you have any clue what the problem might be looking at my code?

**Comment by bhutzler** [comment]
Hallo,
können wir auch auf deutsch weiter schreiben? Deinem Namen nach würde ich tippen, dass Du deutschsprachig bist.
Ich programmiere zwar selbst, kenne mich mit NodeJS/Homebridge noch gar nicht aus.
Im Log sehe ich, dass die Temperaturwerte korrekt ausgelesen werden, aber HomeKit kommt damit wohl nicht zurecht. Bei -0.1 Grad gibt es Probleme. Evtl. auch schon bei 0 Grad.

**Comment by cbrandlehner** [comment]
Ja gerne, Problem verstanden - die Ursache ist mir aktuell unklar.

**Comment by bhutzler** [comment]
Kann es sein, dass das Problem nicht an Deinem PlugIn liegt sondern direkt bei der Homebridge?

**Comment by cbrandlehner** [comment]
Das kann man nicht ausschliessen.

**Comment by cbrandlehner** [comment]
Issue was reported elsewhere too. It is a general HomeBridge issue: [](https://github.com/ebaauw/homebridge-hue/issues/30)

**Comment by cbrandlehner** [comment]
Used the new information to fix the issue in 2019.18.3.
